# Usa Node.js como base
FROM node:18

# Crea y establece el directorio de trabajo
WORKDIR /app

# Copia el package.json y package-lock.json (para instalar dependencias primero)
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto del código
COPY . .

# Expone el puerto en el que corre tu API
EXPOSE 3004

# Comando para iniciar la API
CMD ["node", "server.js"]
